preload = /home/sdelage/Pictures/Wallpaper/587568.jpg
preload = /home/sdelage/Pictures/Wallpaper/1341771.png

wallpaper = DP-2,/home/sdelage/Pictures/Wallpaper/1341771.png
wallpaper = DP-3,/home/sdelage/Pictures/Wallpaper/587568.jpg

splash = false
